server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_posting?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_suho
    password: 1234
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

secret-key: "S1e1c1r1e1t1K1e1yS1e1c1r1e1t1K1e1yS1e1c1r1e1t1K1e1y"